// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealEstateCMS.Data;

#nullable disable

namespace RealEstateCMS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260120181836_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("RealEstateCMS.Data.Models.Building", b =>
                {
                    b.Property<int>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PhaseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BuildingId");

                    b.HasIndex("PhaseId", "Name")
                        .IsUnique();

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            BuildingId = 1,
                            Name = "Blocul A",
                            PhaseId = 1
                        });
                });

            modelBuilder.Entity("RealEstateCMS.Data.Models.Development", b =>
                {
                    b.Property<int>("DevelopmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("DevelopmentId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Developments");

                    b.HasData(
                        new
                        {
                            DevelopmentId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "București, Sector 2",
                            Name = "Green Park Residence"
                        });
                });

            modelBuilder.Entity("RealEstateCMS.Data.Models.HouseType", b =>
                {
                    b.Property<int>("HouseTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("FromPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PhaseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("HouseTypeId");

                    b.HasIndex("PhaseId", "Name")
                        .IsUnique();

                    b.ToTable("HouseTypes");

                    b.HasData(
                        new
                        {
                            HouseTypeId = 1,
                            Bathrooms = 1,
                            Bedrooms = 2,
                            FromPrice = 85000m,
                            IsAvailable = true,
                            IsFeatured = true,
                            Name = "Tip A - 2 camere",
                            PhaseId = 1,
                            PropertyType = "Apartment"
                        });
                });

            modelBuilder.Entity("RealEstateCMS.Data.Models.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AltText")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("ImageId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("OwnerType", "OwnerId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("RealEstateCMS.Data.Models.Phase", b =>
                {
                    b.Property<int>("PhaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DevelopmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("PhaseId");

                    b.HasIndex("DevelopmentId", "Name")
                        .IsUnique();

                    b.ToTable("Phases");

                    b.HasData(
                        new
                        {
                            PhaseId = 1,
                            DevelopmentId = 1,
                            Name = "Faza 1",
                            StartDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("RealEstateCMS.Data.Models.Plot", b =>
                {
                    b.Property<int>("PlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HouseTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsShowHome")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarketingMessage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PlotId");

                    b.HasIndex("HouseTypeId");

                    b.HasIndex("BuildingId", "Number")
                        .IsUnique();

                    b.ToTable("Plots");

                    b.HasData(
                        new
                        {
                            PlotId = 1,
                            BuildingId = 1,
                            HouseTypeId = 1,
                            IsFeatured = true,
                            IsShowHome = false,
                            Level = 1,
                            Name = "Apartament 101",
                            Number = 101,
                            Price = 87500m,
                            Status = "Available"
                        });
                });

            modelBuilder.Entity("RealEstateCMS.Data.Models.Building", b =>
                {
                    b.HasOne("RealEstateCMS.Data.Models.Phase", "Phase")
                        .WithMany("Buildings")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Phase");
                });

            modelBuilder.Entity("RealEstateCMS.Data.Models.HouseType", b =>
                {
                    b.HasOne("RealEstateCMS.Data.Models.Phase", "Phase")
                        .WithMany("HouseTypes")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Phase");
                });

            modelBuilder.Entity("RealEstateCMS.Data.Models.Image", b =>
                {
                    b.HasOne("RealEstateCMS.Data.Models.Building", "Building")
                        .WithMany("Images")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RealEstateCMS.Data.Models.HouseType", "HouseType")
                        .WithMany("Images")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RealEstateCMS.Data.Models.Plot", "Plot")
                        .WithMany("Images")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Building");

                    b.Navigation("HouseType");

                    b.Navigation("Plot");
                });

            modelBuilder.Entity("RealEstateCMS.Data.Models.Phase", b =>
                {
                    b.HasOne("RealEstateCMS.Data.Models.Development", "Development")
                        .WithMany("Phases")
                        .HasForeignKey("DevelopmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Development");
                });

            modelBuilder.Entity("RealEstateCMS.Data.Models.Plot", b =>
                {
                    b.HasOne("RealEstateCMS.Data.Models.Building", "Building")
                        .WithMany("Plots")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RealEstateCMS.Data.Models.HouseType", "HouseType")
                        .WithMany("Plots")
                        .HasForeignKey("HouseTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("HouseType");
                });

            modelBuilder.Entity("RealEstateCMS.Data.Models.Building", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Plots");
                });

            modelBuilder.Entity("RealEstateCMS.Data.Models.Development", b =>
                {
                    b.Navigation("Phases");
                });

            modelBuilder.Entity("RealEstateCMS.Data.Models.HouseType", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Plots");
                });

            modelBuilder.Entity("RealEstateCMS.Data.Models.Phase", b =>
                {
                    b.Navigation("Buildings");

                    b.Navigation("HouseTypes");
                });

            modelBuilder.Entity("RealEstateCMS.Data.Models.Plot", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
